CREATE TABLE access_tokens (
    code UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    value VARCHAR(512) NOT NULL UNIQUE,
    issuer VARCHAR(255) NOT NULL,
    subject UUID NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    expired_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject) REFERENCES users(code)
);
