
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE files (
    "code" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "name" VARCHAR(512) NOT NULL,
    "url" VARCHAR(512) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
