spring.application.name=auth

server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://data-testing/usermanager
spring.datasource.username=webapp
spring.datasource.password=webapp
spring.jpa.open-in-view=True
spring.application.additional-arguments=-Duser.timezone=UTC
spring.jackson.time-zone=UTC
app.server.url=https://auth.example.com
app.oidc.private.keys=${OIDC_PRIVATE_KEYS}
app.oidc.public.keys=${OIDC_PUBLIC_KEYS}
