spring.application.name=auth

server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.open-in-view=True
spring.application.additional-arguments=-Duser.timezone=UTC
spring.jackson.time-zone=UTC
