spring.application.name=auth

server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.application.additional-arguments=-Duser.timezone=UTC
spring.jackson.time-zone=UTC
app.server.url=${SERVER_URL}
app.oidc.private.keys=${OIDC_PRIVATE_KEYS}
app.oidc.public.keys=${OIDC_PUBLIC_KEYS}
